### ISSUE TITLE
Image not getting built

### ISSUE THREAD

**Issue by ApsaraGeek** [BBVA/SALD#2]
The tarkin-check image is not getting built.
`Sending build context to Docker daemon 35.44 MB
Step 1/4 : FROM tarkin-check:latest
repository tarkin-check not found: does not exist or no pull access
Sending build context to Docker daemon 35.44 MB
Step 1/4 : FROM tarkin-check:latest
repository tarkin-check not found: does not exist or no pull access`

while running build.sh script.

**Comment by deccar** [comment]
Hi @ApsaraGeek,

We just succesfully tested the construction of the docker images in OSX and Linux in all the currently active branches of the project. Can you provide us with more details about your environment (python and docker versions, full execution output, etc) so that we can dig deeper into it?

I'm going to push a minor fix to a bug in the build.sh script that probably has nothing to do with your problem. Pull and try again anyway just in case and let us know of the outcome.

Thanks a lot for your help to improve the project!

**Comment by deccar** [comment]
Hi @ApsaraGeek 

I've seen you opened a new issue in which you refer troubles executing the docker image, but it seems like you managed to build it properly, so I'm going to mark this one as closed. Please don't hesitate reopening or sending a new one should you find any other problems.

**Comment by ApsaraGeek** [comment]
Thanks for the support !!!
